# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a96c10e2a9ec3b9cf38dc2373db9f741"
name = "testing-app"
handle = "testing-app-721"
application_url = "https://sea-lion-app-7vmil.ondigitalocean.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "renai-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sea-lion-app-7vmil.ondigitalocean.app/auth/callback",
  "https://sea-lion-app-7vmil.ondigitalocean.app/auth/shopify/callback",
  "https://sea-lion-app-7vmil.ondigitalocean.app/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
